Inventory.Web/Models/ArticlesViewModel.cs
using Inventory.Web.Data.Entities;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Inventory.Web.Models
{
    public class ArticlesViewModel:Article
    {

        [Display(Name = "Image")]
        public IFormFile ImageFile { get; set; }
    }
}

Inventory.Web/Controllers/API/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Inventory.Web.Data;
using Inventory.Web.Data.Entities;
using Inventory.Web.Data.IRepositories;

namespace Inventory.Web.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class ArticlesController : ControllerBase
    {
     
        private readonly IArticleRepository articleRepository;

        public ArticlesController(IArticleRepository articleRepository)
        {
           
            this.articleRepository = articleRepository;
        }

        // GET: api/Articles
        [HttpGet]
        public IActionResult GetArticles()
        {
            return Ok(this.articleRepository.GetAll());
        }

        // GET: api/Articles/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetArticle([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var article = await this.articleRepository.GetByIdAsync(id);

            if (article == null)
            {
                return NotFound();
            }

            return Ok(article);
        }

        // PUT: api/Articles/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutArticle([FromRoute] int id, [FromBody] Article article)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != article.Id)
            {
                return BadRequest();
            }

           

            try
            {
                await this.articleRepository.UpdateAsync(article);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await this.articleRepository.ExistsAsync(article.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Articles
        [HttpPost]
        public async Task<IActionResult> PostArticle([FromBody] Article article)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            await this.articleRepository.CreateAsync(article);

            return CreatedAtAction("GetArticle", new { id = article.Id }, article);
        }

        // DELETE: api/Articles/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteArticle([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var article = await this.articleRepository.GetByIdAsync(id);
            if (article == null)
            {
                return NotFound();
            }

            try
            {
                await this.articleRepository.DeleteAsync(article);
            }
            catch (Exception)
            {

                return RedirectToAction("CannotDelete", "Error");
            }

            return Ok(article);
        }

     
    }
}

Inventory.Web/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Inventory.Web.Data;
using Inventory.Web.Data.Entities;
using Inventory.Web.Data.IRepositories;

using Inventory.Web.Models;
using Inventory.Web.Helpers;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace Inventory.Web.Controllers
{
    public class ArticlesController : Controller
    {
       
        private readonly IArticleRepository articleRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly IZipCodeRepository zipCodeRepository;
        private readonly IAInventoryRepository aInventoryRepository;

        public class ButtonModel
        {
            public string content { get; set; }
            public string cssClass { get; set; }
        }

        public ArticlesController( IArticleRepository articleRepository,ICategoryRepository categoryRepository, IZipCodeRepository zipCodeRepository,IAInventoryRepository aInventoryRepository)
        {
            
            this.articleRepository = articleRepository;
            this.categoryRepository = categoryRepository;
            this.zipCodeRepository = zipCodeRepository;
            this.aInventoryRepository = aInventoryRepository;
        }

        [NonAction]
        // GET: Articles
        public IActionResult Index()
        {
            var dataContext = this.articleRepository.GetAllInclude();
            var articles = this.articleRepository.GetArticles();

         

            return View(dataContext);
        }




        //JSON RESULT
        [HttpPost]
        public IActionResult GetCode(string Code)
        {

            ViewBag.Code = Code;




            return Ok(Code);

        }


        [Route("generate")]
        public IActionResult Generate(string code)
        {
            ViewBag.Code = code;
            ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name");
            ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City");
            return View("Create");
        }

        [Authorize(Roles = "InventoryAdmin, InventoryCRU")]
        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id, int idI)
        {

            if(idI!= 0)
            {
                ViewBag.IdI = idI;
            }


            if (id == null)
            {
                return RedirectToAction("MyBadRequest", "Error");
            }

            ViewBag.id = id;

            var article = await this.articleRepository.GetByIdAsyncInclude(id.Value);
            if (article == null)
            {
                return RedirectToAction("Error404", "Error");
            }

            return View(article);
        }

        [Authorize(Roles = "InventoryAdmin, InventoryCRU")]
        // GET: Articles/Create
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("MyBadRequest", "Error");
            }

            ViewBag.id = id;

            ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name");
            ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City");
            ViewBag.defaultbutton= new ButtonModel() { cssClass = "e-flat", content = "OK" };
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,Code,Name,ZipCodeId,ImageFile")] ArticlesViewModel view, int id)
        {
           
            string articleQuantity = Request.Form["Quantity"];

            if (articleQuantity == "")
            {
                ModelState.AddModelError(string.Empty, "Insert a Quantity, please.");
                ViewBag.id = id;

                ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name");
                ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City");
                ViewBag.defaultbutton = new ButtonModel() { cssClass = "e-flat", content = "OK" };
                return View();
            }

            string addressCheck = Request.Form["Address"];

            if (string.IsNullOrEmpty(addressCheck) || addressCheck == "Please insert your street name")
            {
                ModelState.AddModelError("Address", "Insert a valid address, please.");
                ViewBag.id = id;

                ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name");
                ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City");
                ViewBag.defaultbutton = new ButtonModel() { cssClass = "e-flat", content = "OK" };
                return View();
            }





          

       

            string code = Request.Form["ZipCode"];



            if (code == "0000-000" || string.IsNullOrEmpty(code))
            {

                ModelState.AddModelError("ZipCode", "Please insert a valid ZipCode.");
                ViewBag.id = id;

                ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name");
                ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City");
                ViewBag.defaultbutton = new ButtonModel() { cssClass = "e-flat", content = "OK" };
                return View();
            }

            string sub = code.Substring(4, 1);

            if (sub != "-")
            {
                ModelState.AddModelError("ZipCode", "Please insert a valid ZipCode.");
                ViewBag.id = id;

                ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name");
                ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City");
                ViewBag.defaultbutton = new ButtonModel() { cssClass = "e-flat", content = "OK" };
                return View();
            }

            var getZipCode = this.zipCodeRepository.GetZipCodeByAddress(addressCheck);

            if (getZipCode != null)
            {
                view.ZipCode = getZipCode;
            }

            else
            {
                var zipCode = new ZipCode
                {
                    Code = code,
                    City = "Lisboa",
                    Country = "Portugal",
                    Name = addressCheck,
                    longitude = "0",
                    latitude = "0"
                };

                await this.zipCodeRepository.CreateAsync(zipCode);
                view.ZipCode = zipCode;

            }

            view.Address = addressCheck;


            if (ModelState.IsValid)
            {
               


                var path = string.Empty;
                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.jpg";
                    path = Path.Combine(
                        Directory.GetCurrentDirectory(),
                        "wwwroot\\images\\Articles",
                        file);


                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImageFile.CopyToAsync(stream);
                    }


                    path = $"~/images/Articles/{file}";

                }

               

                var article = this.ToArticle(view, path);

                
                var confirmCodeExists = this.articleRepository.FindArticleByCode(Request.Form["Code"]);
                if(confirmCodeExists== null)
                {
                    var qrCode = GenerateQrCode.GetQRCode(Request.Form["Code"]);
                    var image = qrCode.GetGraphic(5);
                    var convert = ImageConverter.imageToByteArray(image);
                    article.BarCode = convert;




                    await this.articleRepository.CreateAsync(article);
                    var Iarticle = new InventoryArticle
                    {
                        
                        
                        AInventoryId = id,
                        ArticleId = this.articleRepository.GetArticleId(article.Code),
                             
                        Quantity = decimal.Parse(articleQuantity),
                        Unit = "1",
                        Name = article.Name,
                    };

                    await this.aInventoryRepository.CreateInventoryArticleAsync(Iarticle);
                    return RedirectToAction("Index", "InventoryArticles", new { id = id });

                }
                else
                {
                    ModelState.AddModelError("Code", "This Code already exists");
                    ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name", view.CategoryId);
                    ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City", view.ZipCodeId);
                    return View(view);
                }
             
            
            }
            ViewData["CategoryId"] = new SelectList(this.categoryRepository.GetAll(), "Id", "Name", view.CategoryId);
            ViewData["ZipCodeId"] = new SelectList(this.zipCodeRepository.GetAll(), "Id", "City", view.ZipCodeId);
            return View(view);
        }

        private Article ToArticle(ArticlesViewModel view, string path)
        {
            return new Article
            {

Inventory.Web/Views/Articles/Create.cshtml
@model Inventory.Web.Models.ArticlesViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Article</h4>
<hr />


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">

                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" value="@ViewBag.Code" />
                <span asp-validation-for="Code" class="text-danger"></span>

            </div>
            @*<div class="form-group">
        <label asp-for="BarCode" class="control-label"></label>
        <input asp-for="BarCode" class="form-control getLocalidade" id="getAnotherCity" />
        <span asp-validation-for="BarCode" class="text-danger"></span>*@
            @*@if (ViewBag.Code != null)
        {*@
            @*<div class="form-group" id="idPais">
        <label asp-for="BarCode" class="control-label"></label>

        <qrcode content="@ViewBag.Code" name="BarCode"  width="200" height="200"></qrcode>
        <span asp-validation-for="BarCode" class="text-danger"></span>
        </div>*@

            @*//}*@


            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCodeId" class="control-label">Zip Code</label>
                <input asp-for="ZipCode" class="form-control" onchange="javascript:getCities(this.value)" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>

            </div>
            <div class="form-group" id="idOutroPais">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control getLocalidade" id="getAnotherCity" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" type="file" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Quantity</label>
                <input class="form-control" type="number" name="Quantity" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />


            </div>

        </form>
    </div>



</div>

<div>
    <a asp-action="Index" asp-controller="InventoryArticles" asp-route-id="@ViewBag.id">Back to List</a>
</div>

@*<div class="modal fade" id="myModal" role="dialog" >
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <p class="modal-title">Article succesfully created</p>
            </div>
            <div class="modal-body">
               
                    <img src="~/images/Ok.png" height="80" width="80" style="margin:30px;" />
                

            </div>
            <div class="modal-footer">
                <button type="button"  class="btn btn-success" data-dismiss="modal" onclick="GoTo()">OK</button>
            </div>
        </div>
    </div>
</div>*@



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}



@*<script>

    $('#myForm').on('submit', function(e){
  $('#myModal').modal('show');
  e.preventDefault();
    });


    function GoTo() {
        window.location.href = "/InventoryArticles/Index/7";
    };
</script>*@


<script type="text/javascript">

    window.onload = function () {

        $("#idOutroPais").hide();

    }

    function getCities(Code) {
        $.ajax({
            type: 'POST',
            url: "/Clients/GetData",
            cache: false,
            data: { Code },
            success: function (data) {
                $('#getAnotherCity').val(data);

                $("#idOutroPais").show();



            },
            error: function () {
                var ErrorMessage = "please fill with your street name";
                $(".getLocalidade").html(ErrorMessage).show();
                $("#idOutroPais").show();
            }
        });

    }





</script>

Inventory.Web/Views/Articles/Delete.cshtml
@model Inventory.Web.Data.Entities.Article

@{
    ViewData["Title"] = "Delete";
}

<h2>Article</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="col-md-6">
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BarCode)
        </dt>
        <dd>

            @if (Model.BarCode != null)
            {
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.BarCode)" width="120" height="120" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ZipCode.City)
        </dd>

    </dl>


    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <div>
            <a asp-action="Details" asp-controller="Articles" asp-route-id="@ViewBag.id" asp-route-idI="@ViewBag.idI">Back to List</a>

        </div>
    </form>

</div>
<div class="col-md-6">
 
  
    @if (!string.IsNullOrEmpty(Model.ImageUrl))
    {
        <img src="@Url.Content(Model.ImageUrl)" alt="Image" style="width:200px;height:350px;max-width:100%;height:auto" />
    }
</div>

Inventory.Web/Views/Articles/Details.cshtml
@model Inventory.Web.Data.Entities.Article



<h2>Details</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
       
  
  
    </dl>
</div>
<table class="table">
    <thead>
        <tr class="hidden-print">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
         
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
               Locations
            </th>
        </tr>
    </thead>
    <tbody>
      
        <tr>
            <td class="hidden-print">
                @Html.DisplayFor(modelItem => Model.Name)
            </td>
            <td class="hidden-print">
                @Html.DisplayFor(model => model.Category.Name)
            </td>

            <td id="printdivcontent">

                @if (!string.IsNullOrEmpty(Model.ImageUrl))
                {
                    <img  src="@Url.Content(Model.ImageUrl)" alt="Image" style="width:150px;height:225px;max-width:100%;height:auto" />
                }

                @if (Model.BarCode != null)
                {
                    <img  src="data:image;base64,@System.Convert.ToBase64String(Model.BarCode)" width="120" height="120" />
                }
            </td>
            <td class="hidden-print">
                @Html.DisplayFor(model => model.ZipCode.Name),
                @Html.DisplayFor(model => model.ZipCode.City)
                @if (Model.ZipCode.latitude != "0")
                {
                    <img src="@Url.Content($"https://maps.googleapis.com/maps/api/staticmap?center={Model.ZipCode.latitude},{Model.ZipCode.longitude}&zoom=16&size=600x300&maptype=roadmap&markers=color:blue%7C{Model.ZipCode.latitude},{Model.ZipCode.longitude}&key=AIzaSyBpEaGobPxWI7oFrSH1KxVzCp9uzgkwIps")" />
                }
                else
                {


                    <img src="~/images/mapNotAvailable.jpg" style="width:600px;height:300px;" />
                }

            </td>
            <td>


                <div class="dropdown hidden-print">
                    <button class="btn btn-info dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
                        Actions
                        @*<span class="caret"></span>*@
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                        <li role="presentation"><a asp-action="Edit" asp-route-id="@Model.Id" asp-route-idI="@ViewBag.IdI" role="menuitem" tabindex="-1">Edit</a> </li>

                        <li role="presentation"><a asp-action="Delete" asp-route-id="@Model.Id" asp-route-idI="@ViewBag.IdI" role="menuitem" tabindex="-1">Delete</a></li>

                    </ul>
                </div>


            </td>
            <td>
                <div class="hidden-print">
                    <button id="btn" class="btn btn-info hidden-print" onclick="PrintDiv();"> Print <span class="glyphicon glyphicon-print"></span></button>

                </div>

            </td>
        </tr>
       
    </tbody>
</table>

<div>
   
    <a asp-action="Index" asp-controller="InventoryArticles" asp-route-id="@ViewBag.IdI">Back to List</a>
</div>

<script type="text/javascript">
    function PrintDiv() {
        var divContents = document.getElementById("printdivcontent").innerHTML;
        var printWindow = window.open('', '', 'height=1000,width=1000');
        printWindow.document.write('<html><head><title>Print</title>');
        printWindow.document.write('</head><body >');
        printWindow.document.write(divContents);
        printWindow.document.write(divContents);
        printWindow.document.write(divContents);
        printWindow.document.write(divContents);
        printWindow.document.write(divContents);
         printWindow.document.write(divContents);


        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }
</script>

Inventory.Web/Views/Articles/Edit.cshtml
@model Inventory.Web.Models.ArticlesViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ImageUrl" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId" readonly="readonly" disabled="disabled"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" readonly="readonly" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="BarCode" class="control-label"></label>
                <input asp-for="BarCode" class="form-control" />
                <span asp-validation-for="BarCode" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCodeId" class="control-label">Zip Code</label>
                <select asp-for="ZipCodeId" class="form-control" asp-items="ViewBag.ZipCodeId" disabled="disabled" ></select>
                <span asp-validation-for="ZipCodeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" type="file" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Quantity</label>
                <input class="form-control" type="number" name="Quantity" value="@ViewBag.Quant" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" asp-route-idI="@ViewBag.idI" />
            </div>
        </form>
    </div>
        @if (!string.IsNullOrEmpty(Model.ImageUrl))
        {
            <img src="@Url.Content(Model.ImageUrl)" alt="noimage" style="width:150px;height:150px;max-width:100%;" />
        }
</div>

<div>
    <a asp-action="Details" asp-controller="Articles" asp-route-id="@ViewBag.id" asp-route-idI="@ViewBag.idI">Back to List</a>
 
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inventory.Web/Views/Articles/Index.cshtml
@model IEnumerable<Inventory.Web.Data.Entities.Article>

@{
    ViewData["Title"] = "Index";
}

<h2 class="hidden-print">Index</h2>



<p class="hidden-print">
    <a class="hidden-print" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead class="hidden-print">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BarCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="hidden-print">
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>

                <td id="printdivcontent">
                    @if (item.BarCode != null)
                    {
                        <img src="data:image;base64,@System.Convert.ToBase64String(item.BarCode)" width="120" height="120" />
                    }

                </td>
                <td class="hidden-print">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="hidden-print">

                    @Html.DisplayFor(modelItem => item.ZipCode.Name),
                    @Html.DisplayFor(modelItem => item.ZipCode.City)
                    @if (item.ZipCode != null)
                    {
                        <img src="@Url.Content($"https://maps.googleapis.com/maps/api/staticmap?center={item.ZipCode.latitude},{item.ZipCode.longitude}&zoom=16&size=600x300&maptype=roadmap&markers=color:blue%7C{item.ZipCode.latitude},{item.ZipCode.longitude}&key=AIzaSyBpEaGobPxWI7oFrSH1KxVzCp9uzgkwIps")" />
                    }
                </td>
                <td class="hidden-print">
                    <div class="dropdown">
                        <button class="btn btn-info dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
                            Actions
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                            <li  role="presentation"><a asp-action="Edit" asp-route-id="@item.Id" role="menuitem" tabindex="-1">Edit</a> </li>
                            <li role="presentation"><a asp-action="Details" asp-route-id="@item.Id" role="menuitem" tabindex="-1">Details</a></li>
                            <li role="presentation"><a asp-action="Delete" asp-route-id="@item.Id" role="menuitem" tabindex="-1">Delete</a></li>
                          
                        </ul>
                    </div>
                 
                </td>
                <td>
                    <div class="hidden-print">
                        <button id="btn" class="btn btn-info hidden-print" onclick="PrintDiv();"> Print <span class="glyphicon glyphicon-print"></span></button>

                    </div>
                    
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    function PrintDiv() {
        var divContents = document.getElementById("printdivcontent").innerHTML;
        var printWindow = window.open('', '', 'height=1000,width=1000');
        printWindow.document.write('<html><head><title>Print</title>');
        printWindow.document.write('</head><body >');
        printWindow.document.write(divContents);
     

        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }
</script>